---
deployment:
  tasks:
    - |
      if [ ! -f .deploy.conf ]
      then
          cp .deploy.example.conf .deploy.conf
          exit
      else
          source .deploy.conf
      fi

    # Set var
    - export DEPLOY_LOG="$DEPLOY_PATH/.deploy.log"
    - export DEPLOY_LIST="$DEPLOY_PATH/.deployed-files.txt"

    # Create paths
    - mkdir -p $DEPLOY_PATH

    # Start deployment
    - echo "Deployment started" > "$DEPLOY_LOG"

    # Remove old files
    - |
      if [ -f "$DEPLOY_LIST" ]
      then
        while IFS= read -r -d $'\0' file; do
          if [ ! -d "$DEPLOY_PATH/$file" ]
          then
            echo "Removing file: $file" >> "$DEPLOY_LOG"
            rm -rf "$DEPLOY_PATH/$file"
          fi
        done < "$DEPLOY_LIST"
      fi

    # Copy new files
    - |
      find -mindepth 1 \
          ! -path "*/.git*" \
          ! -name ".cpanel.yml" \
          ! -name ".deploy.conf" \
          ! -name ".deploy.example.conf" \
          -exec echo "Copying {}" >> "$DEPLOY_LOG" && cp -RTpu "{}" "$DEPLOY_PATH/{}" \;\
          -fprint0 "$DEPLOY_LIST"
