---
deployment:
  tasks:
    # If .deploy.conf doesn't exist, create it from .deploy.example.conf
    - |
      if [ ! -f .deploy.conf ]
      then
          cp .deploy.example.conf .deploy.conf
          exit
      else
          source .deploy.conf
      fi
    
    # Set variables
    - export DEPLOY_LIST="$DEPLOY_PATH/.deployed-files.txt"

    # Create deployment path if it doesn't exist
    - if [ ! -d "$DEPLOY_PATH" ]; then mkdir -p "$DEPLOY_PATH"; fi

    # Remove old files and empty directories
    - |
      if [ -f "$DEPLOY_LIST" ]
      then
        tac "$DEPLOY_LIST" | while read file; do
          if [ -d "$DEPLOY_PATH/$file" ] && [ ! "$(ls -A "$DEPLOY_PATH/$file")" ]
          then
            rmdir "$DEPLOY_PATH/$file"
          elif [ -f "$DEPLOY_PATH/$file" ]
          then
            rm "$DEPLOY_PATH/$file"
          fi
        done
      fi

    # Copy new files
    - |
      find -mindepth 1 \
          ! -path "*/.git*" \
          ! -name ".cpanel.yml" \
          ! -name ".deploy.conf" \
          ! -name ".deploy.example.conf" \
          -exec cp -RTpu "{}" "$DEPLOY_PATH/{}" \;\
          -fprint "$DEPLOY_LIST"
